name: LocaltonetVds

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Downloading Localtonet Please Wait.

      run: |

        Invoke-WebRequest https://localtonet.com/download/win-64.zip -OutFile localtonet.zip

        Invoke-WebRequest https://raw.githubusercontent.com/ShiftyTR/FreeVDSServer/main/start.bat -OutFile start.bat

        Invoke-WebRequest https://raw.githubusercontent.com/ShiftyTR/FreeVDSServer/main/wallpaper.jpg -OutFile wallpaper.jpg

        Invoke-WebRequest https://raw.githubusercontent.com/ShiftyTR/FreeVDSServer/main/wallpaper.bat -OutFile wallpaper.bat

    - name: Extracting Localtonet Files.

      run: Expand-Archive localtonet.zip

    - name: Activating RDP access.

      run: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

        copy wallpaper.jpg D:\a\wallpaper.jpg

        copy wallpaper.bat D:\a\wallpaper.bat

    - name: Connecting to your RDP.

      run: cmd /c start.bat

    - name: Your RDP is ready go localtonet.com and start tcp tunnel 3389 port

      run: .\localtonet\localtonet.exe authtoken $Env:LOCALTONET_AUTH_TOKEN

      env:

        LOCALTONET_AUTH_TOKEN: ${{ secrets.LOCALTONET_AUTH_TOKEN }}?
